"""
Django settings for oduma_platform project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bu-u^(x&*qllbv-@16pwnweq$^j5qv#gwb$@3t2@rnvv2hu5o-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0', 'odumaconnect.onrender.com']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oduma_platform.core',
    # 'oduma_platform.templates',
    'tailwind',

    # 'theme',
    # 'django_browser_reload',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'oduma_platform.urls'

INTERNAL_IPS = [
    "127.0.0.1",
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates/')],
        # 'DIRS': [os.path.join(BASE_DIR,'app/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.app.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'oduma_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': dj_database_url.config(default='postgres://austin:WPnHyrtaq6mPjwTummEEtz4EMQtN7PON@dpg-cvj2kl6uk2gs73b0vkb0-a:5432/odumaconnect')
    # 'default': dj_database_url.config(default='postgresql://austin:WPnHyrtaq6mPjwTummEEtz4EMQtN7PON@dpg-cvj2kl6uk2gs73b0vkb0-a.oregon-postgres.render.com:5432/odumaconnectdb')

    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
    # postgresql://austin:WPnHyrtaq6mPjwTummEEtz4EMQtN7PON@dpg-cvj2kl6uk2gs73b0vkb0-a.oregon-postgres.render.com/odumaconnectdb
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',

        #  'USER': 'austin',
        # 'PASSWORD': 'L@ndM1ne',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    # }
    #     'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'odumaconnectdb',
    #     'USER': 'austin',
    #     'PASSWORD': 'WPnHyrtaq6mPjwTummEEtz4EMQtN7PON',
    #     # 'HOST': 'localhost',
    #     'HOST': 'odumaconnect.onrender.com',
    #     # 'HOST': 'postgresql://austin:WPnHyrtaq6mPjwTummEEtz4EMQtN7PON@dpg-cvj2kl6uk2gs73b0vkb0-a/odumaconnectdb',
    #     'PORT': '5432',
    # }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'yourdbname',
       
#     }
# }


STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIR = [os.path.join( BASE_DIR,'core/')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'core.CustomUser'

# TAILWIND_APP_NAME = 'theme'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/'


